import type { RenovateConfig } from '@/types'

export const defaultConfig: RenovateConfig = {
  $schema: 'https://docs.renovatebot.com/renovate-schema.json',
  extends: [],
  enabled: true,
  dependencyDashboard: true,
  pinDigests: true,
  timezone: 'UTC',
  gitAuthor: 'Renovate Bot <bot@renovateapp.com>',
  semanticCommits: 'auto',
  prHourlyLimit: 0,
  prConcurrentLimit: 0,
  rebaseWhen: 'auto',
  schedule: [],
  automerge: false,
  automergeType: 'pr',
  rangeStrategy: 'auto',
  major: { automerge: false },
  minor: { automerge: false },
  patch: { automerge: false },
  lockFileMaintenance: {
    enabled: true,
    automerge: true,
    schedule: [],
  },
  labels: [],
  assignees: [],
  reviewers: [],
  packageRules: [],
  automergeSchedule: [],
  baseBranchPatterns: [],
  branchName: '',
  branchTopic: '',
  vulnerabilityAlerts: 'none',
  ignoreDeps: [],
  ignorePaths: [],
}
